// Regression Test 2
// Checks whether multifiles compiled with -mlocal-offsets produces proper offsets.
//
// RUN: %gta3sc-filecheck %s --config=gta3 -mlocal-offsets -emit-ir2 -o -
//
LAUNCH_MISSION subscript.sc
LOAD_AND_LAUNCH_MISSION miss1.sc
main_label:
GOTO main_label
TERMINATE_THIS_SCRIPT

// CHECK-NEXT: LAUNCH_MISSION %MAIN_2
// CHECK-NEXT: LOAD_AND_LAUNCH_MISSION_INTERNAL 0i8
// CHECK-NEXT: MAIN_1:
// CHECK-NEXT: GOTO %MAIN_1
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: MAIN_2:
// CHECK-NEXT: SCRIPT_NAME 'SUBSC'
// CHECK-NEXT: MAIN_3:
// CHECK-NEXT: GOTO %MAIN_3
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: #MISSION_BLOCK_START 0
// CHECK-NEXT: SCRIPT_NAME 'MISS1'
// CHECK-NEXT: MISSION_0_1:
// CHECK-NEXT: GOTO %MISSION_0_1
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: #MISSION_BLOCK_END
