// Regression Test 4
// Ensures file includers when used from subscripts onwards uses labels.
//
// RUN: %gta3sc %s --config=gta3 -emit-ir2 -o - | %FileCheck %s
//
LAUNCH_MISSION subscript.sc
LOAD_AND_LAUNCH_MISSION miss1.sc
TERMINATE_THIS_SCRIPT

// CHECK-NEXT: LAUNCH_MISSION @MAIN_1
// CHECK-NEXT: LOAD_AND_LAUNCH_MISSION_INTERNAL 0i8
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: MAIN_1:
// CHECK-NEXT: SCRIPT_NAME 'SUBSC'
// CHECK-NEXT: GOSUB_FILE @MAIN_2 @MAIN_2
// CHECK-NEXT: LAUNCH_MISSION @MAIN_2
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: MAIN_2:
// CHECK-NEXT: GOTO @MAIN_2
// CHECK-NEXT: #MISSION_BLOCK_START 0
// CHECK-NEXT: SCRIPT_NAME 'MISS1'
// CHECK-NEXT: GOSUB_FILE %MISSION_0_1 %MISSION_0_1
// CHECK-NEXT: LAUNCH_MISSION %MISSION_0_1
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: MISSION_0_1:
// CHECK-NEXT: GOTO %MISSION_0_1
// CHECK-NEXT: #MISSION_BLOCK_END
