// RUN: %gta3sc-filecheck %s --config=gta3 -emit-ir2 -o -

VAR_INT x

// CHECK-NEXT: ANDOR 0i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_1
IF x = 0
    // CHECK-NEXT: WAIT 1i8
    WAIT 1
ENDIF

// CHECK-NEXT: MAIN_1:
// CHECK-NEXT: ANDOR 2i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 3i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_2
IF  x = 1
AND x = 2
AND x = 3
    // CHECK-NEXT: WAIT 3i8
    WAIT 3
ENDIF

// CHECK-NEXT: MAIN_2:
// CHECK-NEXT: ANDOR 22i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 3i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_3
IF x = 1
OR x = 2
OR x = 3
    // CHECK-NEXT: WAIT 2i8
    WAIT 2
ENDIF

// CHECK-NEXT: MAIN_3:
// CHECK:      IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: NOT IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
IF x = 1
OR NOT x = 2
    WAIT 0
ENDIF

TERMINATE_THIS_SCRIPT