// RUN: %gta3sc-filecheck %s --config=gtavc -emit-ir2 -o -

VAR_INT x

// CHECK-NEXT: ANDOR 0i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_1
IF x = 0
    // CHECK-NEXT: WAIT 1i8
    // CHECK-NEXT: NOP
    WAIT 1
    NOP
ENDIF

// CHECK-NEXT: MAIN_1:
// CHECK-NEXT: ANDOR 0i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_2
IF x = 0
    // CHECK-NEXT: WAIT 2i8
    // CHECK-NEXT: NOP
    // CHECK-NEXT: GOTO @MAIN_3
    WAIT 2
    NOP
ELSE
    // CHECK-NEXT: MAIN_2:
    // CHECK-NEXT: WAIT 3i8
    // CHECK-NEXT: NOP
    WAIT 3
    NOP
ENDIF

// CHECK-NEXT: MAIN_3:
// CHECK-NEXT: ANDOR 0i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_4
WHILE x = 0
    // CHECK-NEXT: WAIT 10i8
	// CHECK-NEXT: NOP
    // CHECK-NEXT: GOTO @MAIN_3
    WAIT 10
	NOP
ENDWHILE

// CHECK-NEXT: MAIN_4:
// CHECK-NEXT: SET_VAR_INT &8 0i8
REPEAT 10 x
    // CHECK-NEXT: MAIN_5:
    // CHECK-NEXT: WAIT 11i8
	// CHECK-NEXT: NOP
    WAIT 11
	NOP
    // CHECK-NEXT: ADD_VAL_TO_INT_VAR &8 1i8
    // CHECK-NEXT: IS_INT_VAR_GREATER_OR_EQUAL_TO_NUMBER &8 10i8
    // CHECK-NEXT: GOTO_IF_FALSE @MAIN_5
ENDREPEAT

// CHECK-NEXT: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT