// Emulated IFNOT/WHILENOT when GOTO_IF_TRUE unsupported.
// RUN: %gta3sc %s --config=gtavc -fifnot -emit-ir2 -o - | %FileCheck %s

VAR_INT x

// CHECK-NEXT-L: ANDOR 0i8
// CHECK-NEXT-L: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_1
// CHECK-NEXT-L: GOTO @MAIN_2
IFNOT x = 0
    // CHECK-NEXT-L: MAIN_1:
    // CHECK-NEXT-L: WAIT 1i8
    // CHECK-NEXT-L: NOP
    WAIT 1
    NOP
ENDIF

// CHECK-NEXT-L: MAIN_2:
// CHECK-NEXT-L: ANDOR 0i8
// CHECK-NEXT-L: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_3
IFNOT x = 0
    // CHECK-NEXT-L: WAIT 3i8
    // CHECK-NEXT-L: NOP
    // CHECK-NEXT-L: GOTO @MAIN_4
    // CHECK-NEXT-L: MAIN_3:
    // CHECK-NEXT-L: WAIT 2i8
    // CHECK-NEXT-L: NOP
    WAIT 2
    NOP
ELSE
    WAIT 3
    NOP
ENDIF

// CHECK-NEXT-L: MAIN_4:
// CHECK-NEXT-L: ANDOR 0i8
// CHECK-NEXT-L: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT-L: GOTO_IF_FALSE @MAIN_5
// CHECK-NEXT-L: GOTO @MAIN_6
WHILENOT x = 0
    // CHECK-NEXT-L: MAIN_5:
    // CHECK-NEXT-L: WAIT 10i8
    // CHECK-NEXT-L: NOP
    // CHECK-NEXT-L: GOTO @MAIN_4
    WAIT 10
    NOP
ENDWHILE

// CHECK-NEXT-L: MAIN_6:
// CHECK-NEXT-L: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT
