// RUN: %gta3sc %s --config=gta3 -emit-ir2 -o - | %FileCheck %s

VAR_INT x

// CHECK-NEXT: ANDOR 0i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT: GOTO_IF_TRUE @MAIN_1
IFNOT x = 0
    // CHECK-NEXT: WAIT 1i8
    // CHECK-NEXT: NOP
    WAIT 1
    NOP
ENDIF

// CHECK-NEXT: MAIN_1:
// CHECK-NEXT: ANDOR 0i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT: GOTO_IF_TRUE @MAIN_2
IFNOT x = 0
    // CHECK-NEXT: WAIT 2i8
    // CHECK-NEXT: NOP
    // CHECK-NEXT: GOTO @MAIN_3
    WAIT 2
    NOP
ELSE
    // CHECK-NEXT: MAIN_2:
    // CHECK-NEXT: WAIT 3i8
    // CHECK-NEXT: NOP
    WAIT 3
    NOP
ENDIF

// CHECK-NEXT: MAIN_3:
// CHECK-NEXT: ANDOR 0i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 0i8
// CHECK-NEXT: GOTO_IF_TRUE @MAIN_4
WHILENOT x = 0
    // CHECK-NEXT: WAIT 10i8
    // CHECK-NEXT: NOP
    // CHECK-NEXT: GOTO @MAIN_3
    WAIT 10
    NOP
ENDWHILE

// CHECK-NEXT: MAIN_4:
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT
