// Emulated IFNOT/WHILENOT AND/OR when GOTO_IF_TRUE unsupported.
// RUN: %gta3sc %s --config=gtavc -fifnot -emit-ir2 -o - | %FileCheck %s

VAR_INT x

// CHECK-NEXT: ANDOR 2i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 3i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_1
// CHECK-NEXT: GOTO @MAIN_2
IFNOT x = 1
AND x = 2
AND x = 3
    // CHECK-NEXT: MAIN_1:
    // CHECK-NEXT: WAIT 1i8
    // CHECK-NEXT: NOP
    WAIT 1
    NOP
ENDIF

// CHECK-NEXT: MAIN_2:
// CHECK-NEXT: ANDOR 22i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 3i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_3
// CHECK-NEXT: GOTO @MAIN_4
IFNOT x = 1
OR x = 2
OR x = 3
    // CHECK-NEXT: MAIN_3:
    // CHECK-NEXT: WAIT 2i8
    // CHECK-NEXT: NOP
    WAIT 2
    NOP
ENDIF

// CHECK-NEXT: MAIN_4:
// CHECK-NEXT: ANDOR 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_5
IFNOT x = 1
AND x = 2
    // CHECK-NEXT: WAIT 4i8
    // CHECK-NEXT: NOP
    // CHECK-NEXT: GOTO @MAIN_6
    // CHECK-NEXT: MAIN_5:
    // CHECK-NEXT: WAIT 3i8
    // CHECK-NEXT: NOP
    WAIT 3
    NOP
ELSE
    WAIT 4
    NOP
ENDIF

// CHECK-NEXT: MAIN_6:
// CHECK-NEXT: ANDOR 21i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_7
IFNOT x = 1
OR x = 2
    // CHECK-NEXT: WAIT 6i8
    // CHECK-NEXT: NOP
    // CHECK-NEXT: GOTO @MAIN_8
    // CHECK-NEXT: MAIN_7:
    // CHECK-NEXT: WAIT 5i8
    // CHECK-NEXT: NOP
    WAIT 5
    NOP
ELSE
    WAIT 6
    NOP
ENDIF

// CHECK-NEXT: MAIN_8:
// CHECK-NEXT: ANDOR 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_9
// CHECK-NEXT: GOTO @MAIN_10
WHILENOT x = 1
AND x = 2
    // CHECK-NEXT: MAIN_9:
    // CHECK-NEXT: WAIT 10i8
    // CHECK-NEXT: NOP
    // CHECK-NEXT: GOTO @MAIN_8
    WAIT 10
    NOP
ENDWHILE

// CHECK-NEXT: MAIN_10:
// CHECK-NEXT: ANDOR 21i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 1i8
// CHECK-NEXT: IS_INT_VAR_EQUAL_TO_NUMBER &8 2i8
// CHECK-NEXT: GOTO_IF_FALSE @MAIN_11
// CHECK-NEXT: GOTO @MAIN_12
WHILENOT x = 1
OR x = 2
    // CHECK-NEXT: MAIN_11:
    // CHECK-NEXT: WAIT 11i8
    // CHECK-NEXT: NOP
    // CHECK-NEXT: GOTO @MAIN_10
    WAIT 11
    NOP
ENDWHILE

// CHECK-NEXT: MAIN_12:
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT
