// RUN: %gta3sc %s --config=gta3 -emit-ir2 -o - | %FileCheck %s
// # SCM Header, Alignment and such performed by test/main-test-gta3/

// Put declarations out of order, so we can ensure miss2 ordering.

// CHECK-NEXT: GOSUB @MAIN_3
GOSUB gosub2

// CHECK-NEXT: GOSUB_FILE @MAIN_2 @MAIN_2
GOSUB_FILE gosub1 gosub1.sc

// CHECK-NEXT: LAUNCH_MISSION @MAIN_5
LAUNCH_MISSION subscript1.sc

// CHECK-NEXT: LOAD_AND_LAUNCH_MISSION_INTERNAL 0i8
LOAD_AND_LAUNCH_MISSION mission1.sc

// CHECK-NEXT: LAUNCH_MISSION @MAIN_6
LAUNCH_MISSION subscript2.sc

// CHECK-NEXT: GOSUB_FILE @MAIN_3 @MAIN_3
GOSUB_FILE gosub2 gosub2.sc

// CHECK-NEXT: LOAD_AND_LAUNCH_MISSION_INTERNAL 1i8
LOAD_AND_LAUNCH_MISSION mission2.sc

// CHECK-NEXT: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT

// gosub1.sc
// CHECK-NEXT: MAIN_1:
// CHECK-NEXT: RETURN
// CHECK-NEXT: MAIN_2:
// CHECK-NEXT: PRINT_HELP 'GOSUB1'
// CHECK-NEXT: GOTO @MAIN_1

// gosub2.sc
// CHECK-NEXT: MAIN_3:
// CHECK-NEXT: PRINT_HELP 'GOSUB2'
// CHECK-NEXT: GOSUB_FILE @MAIN_4 @MAIN_4
// CHECK-NEXT: RETURN

// gosub3.sc
// CHECK-NEXT: MAIN_4:
// CHECK-NEXT: PRINT_HELP 'GOSUB3'
// CHECK-NEXT: LOAD_AND_LAUNCH_MISSION_INTERNAL 2i8
// CHECK-NEXT: RETURN

// subscript1.sc
// CHECK-NEXT: MAIN_5:
// CHECK-NEXT: PRINT_HELP 'SUBSC1'
// CHECK-NEXT: TERMINATE_THIS_SCRIPT

// subscript2.sc
// CHECK-NEXT: MAIN_6:
// CHECK-NEXT: PRINT_HELP 'SUBSC2'
// CHECK-NEXT: TERMINATE_THIS_SCRIPT

// mission1.sc
// CHECK-NEXT: #MISSION_BLOCK_START 0
// CHECK-NEXT: PRINT_HELP 'MISS1'
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: #MISSION_BLOCK_END

// mission2.sc
// CHECK-NEXT: #MISSION_BLOCK_START 1
// CHECK-NEXT: PRINT_HELP 'MISS2'
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: #MISSION_BLOCK_END

// mission3.sc
// CHECK-NEXT: #MISSION_BLOCK_START 2
// CHECK-NEXT: PRINT_HELP 'MISS3'
// CHECK-NEXT: TERMINATE_THIS_SCRIPT
// CHECK-NEXT: #MISSION_BLOCK_END
