// RUN: %gta3sc-filecheck %s --config=gtasa --guesser -emit-ir2 -o -

// CHECK: SKIP_CUTSCENE_START_INTERNAL @MAIN_1
SKIP_CUTSCENE_START
// CHECK-NEXT: WAIT 2i8
// CHECK-NEXT: WAIT 3i8
WAIT 2
WAIT 3
// CHECK-NEXT: MAIN_1:
// CHECK-NEXT: SKIP_CUTSCENE_END
SKIP_CUTSCENE_END

// CHECK-NEXT: TERMINATE_THIS_SCRIPT
TERMINATE_THIS_SCRIPT
